# image will be published to ghcr.io/<user>/<name>
name: my-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: gts # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
       - nextcloud-client
       - nextcloud-client-nautilus
      # - micro
      # - starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.microsoft.Edge
        - net.mullvad.MullvadBrowser
        - org.onlyoffice.desktopeditors
        - one.ablaze.floorp
        - com.github.zadam.trilium
        - com.sindresorhus.Caprine
        - org.signal.Signal
        - io.github.shiftey.Desktop
        - org.kde.okular
        - org.gnome.DejaDup
        - com.discordapp.Discord
        - com.github.iwalton3.jellyfin-media-player
        - org.localsend.localsend_app
        - com.github.zocker_160.SyncThingy
        - io.github.fabrialberio.pinapp
        - com.bitwarden.desktop
          # - org.mozilla.firefox
          # - org.gnome.Loupe
          # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
          # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

        # only normal flatpak applications are (like Floorp Lightning web browser in this example).
        # Installing different branches of the same Flatpak is not supported.
      remove:
       # - org.gnome.eog
        - org.mozilla.Thunderbird
        - org.mozilla.firefox
  - type: gnome-extensions
    install:
      - weatheroclockCleoMenezesJr.github.io.v11
      - panoelhan.io.v22
      - just-perfection-desktopjust-perfection.v28
      - caffeinepatapon.info.v54
      - quick-settings-tweaksqwreey.v25
      - status-area-horizontal-spacingmathematical.coffee.gmail.com.v26
      - thinkpad-battery-thresholdmarcosdalvarez.org.v44
      - thinkpadthermalmoonlight.drive.vk.gmail.com.v26
  - type: bling
    install:
    # - ublue-update # https://github.com/ublue-os/ublue-update
    # - 1password # install 1Password (stable) and `op` CLI tool
    # - dconf-update-service # a service unit that updates the dconf db on boot
    # - gnome-vrr # enables gnome-vrr for your image
      - laptop # installs TLP and configures your system for laptop usage
    # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
